name: Triggered manually via workflow_dispatch to promote image to QA.

on:
  workflow_dispatch:
    inputs:
      promote_from:
        description: "Source environment"
        required: true
        default: "dev"
      promote_to:
        description: "Target environment"
        required: true
        default: "qa"

permissions:
  contents: write
  pull-requests: write

jobs:
  docker-build-and-scan:
    name: Docker Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ github.sha }}
          restore-keys: docker-

      - name: Build Docker Image
        run: |
          IMAGE_TAG=springboot-app:${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG .

      - name: Scan Docker Image with Trivy and export report
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          severity: CRITICAL,HIGH
          scan-ref: ${{ env.IMAGE_TAG }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          output: "trivy-image-report.txt"

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          DOCKER_HUB_TAG=${{ secrets.DOCKER_USERNAME }}/csi-pharma-qa:${{ github.sha }}
          docker tag $IMAGE_TAG $DOCKER_HUB_TAG
          docker push $DOCKER_HUB_TAG

